### ISSUE TITLE
Need to support Support 28

### ISSUE THREAD

**Issue by dannybduval** [jainsahab/AndroidSnooper#22]
Way to reproduce:
Client App with the following:

- Target SDK 28
- Build Tools 28.03
- Support Library (especially design), 28.0.0
- AGP 3.3.2
- Gradle Version 5.1.1
- Include`Snooper-Spring` or `Snooper-OKHttp`, the dependency for `Snooper` will get pulled in by which ever you use. In our case, we have both and `Snooper-Spring` brought in `Snooper`
- Make network call
- Go to `HttpCallListActivity`
- Tap on something to get to `HttpCallActivity`

You will get an exception similar to this:

```
06-03 12:39:40.824 6596-6596/com.vaa.runway.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my.package.dev, PID: 6596
    java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Landroid/support/design/widget/TabLayout$OnTabSelectedListener;)V in class Landroid/support/design/widget/TabLayout; or its super classes (declaration of 'android.support.design.widget.TabLayout' appears in /data/app/com.my.package.dev-1/base.apk:classes10.dex)
        at com.prateekj.snooper.networksnooper.activity.HttpCallActivity.setupUi(HttpCallActivity.java:82)
        at com.prateekj.snooper.networksnooper.activity.HttpCallActivity.onCreate(HttpCallActivity.java:69)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

It does not matter if you exclude the support group or if the hosting application pulls in design via implementation or api, it will always crash here.

To get around this, I had to:

- clone the repository
- changed all support to be 28 (it is ideal as Studio will lint a host application for using a different version than the target).
- run `./gradlew publish`
- copied the aars and referenced a local maven repository from `gradle/wrapper/gradle-wrapper.properties` (e.g., `localSnooperLibaryRoot`)
- added the needed check sums, modified the group to avoid conflicts
- recompile
- It now works properly

I also tested this out locally by changing `implementation` to `api` while keeping the support as 27, but that didn't work.

One path I did not check was reducing the target to 27 to keep it in line with guidelines to align target + support pre-AndroidX

**Comment by jainsahab** [comment]
@dannybduval Thanks for reporting this issue, I was able to replicate this on my Android device too. I've migrated Snooper to AndroidX and that seems to have solved this problem. 

I'll be releasing a new version soon and will notify you.

**Comment by dannybduval** [comment]
Equally as good!

**Comment by jainsahab** [comment]
@dannybduval V1.5.4 has been released to the maven central, let me know if you face any more issues.

**Comment by dannybduval** [comment]
will do, right now about 90% done with moving to AndroidX, so I'll really just be looking at it from that perspective. Both from 1.5.3 and 1.5.4 (should be ok both ways since ` com.google.android.material:material:1.0.0` resolves the legacy dependencies independently, e.g., `androidx.legacy:legacy-support-core-ui:1.0.0 `)

**Comment by jainsahab** [comment]
Thanks @dannybduval , I am closing this issue for now. Feel free to comment here if the need arises.

**Comment by dannybduval** [comment]
Same set up as above, but now with moving to Android x, the dependency is `com.google.android.material:material::1.0.0`.

Using 1.5.3, the result is the same, but the stack trace has changed due to how the transient dependencies resolve under AndroidX.

```
java.lang.NoSuchMethodError: No virtual method addOnTabSelectedListener(Lcom/google/android/material/tabs/TabLayout$OnTabSelectedListener;)V in class Lcom/google/android/material/tabs/TabLayout; or its super classes (declaration of 'com.google.android.material.tabs.TabLayout' appears in /data/app/com.delta.mobile.android.dev-1/base.apk)
        at com.prateekj.snooper.networksnooper.activity.HttpCallActivity.setupUi(HttpCallActivity.java:82)
        at com.prateekj.snooper.networksnooper.activity.HttpCallActivity.onCreate(HttpCallActivity.java:69)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
```

If I change the dependency to 1.5.4, it all works as expected.

You may want to retire 1.5.3 from Maven. If people are at least using AGP 3.3, a retired dependency should raise a lint error. As long as they have not overridden `android.lintOptions.abortOnError`, they should be stopped at build time.

**Comment by jainsahab** [comment]
I didn't know if it is possible, Thanks @dannybduval for the suggestion. I'll try and see if I can retire/deprecate that version.
