### ISSUE TITLE
Crash when switching to request or header tabs

### ISSUE THREAD

**Issue by bryancaray** [jainsahab/AndroidSnooper#23]
i am using androidX.
    java.lang.IncompatibleClassChangeError: Class 'com.prateekj.snooper.networksnooper.activity.HttpCallActivity$1' does not implement interface 'com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener' in call to 'void com.google.android.material.tabs.TabLayout$BaseOnTabSelectedListener.onTabUnselected(com.google.android.material.tabs.TabLayout$Tab)' (declaration of 'com.google.android.material.tabs.TabLayout$1' appears in base.apk)
        at com.google.android.material.tabs.TabLayout$1.onTabUnselected(TabLayout.java:825)
        at com.google.android.material.tabs.TabLayout.dispatchTabUnselected(TabLayout.java:1798)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1782)
        at com.google.android.material.tabs.TabLayout.selectTab(TabLayout.java:1745)
        at com.google.android.material.tabs.TabLayout$Tab.select(TabLayout.java:2136)
        at com.google.android.material.tabs.TabLayout$TabView.performClick(TabLayout.java:2324)
        at android.view.View.performClickInternal(View.java:6585)
        at android.view.View.access$3100(View.java:785)
        at android.view.View$PerformClick.run(View.java:25921)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6861)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by jainsahab** [comment]
Thanks, @bryancaray for reporting this. I'll take a look and fix this as soon as possible. but that'll most likely be happening on Weekend. 😅

**Comment by jainsahab** [comment]
Hi @bryancaray , What version of `com.google.android.material` you are using ?

Looks like this library has some breaking changes which caused this issue. you can see [this](https://stackoverflow.com/a/52899027/2911348). 

If you lock in your version dependency to `implementation 'com.google.android.material:material:1.0.0'`, it should work. They've maintained the backward compatibility in this version. I didn't know which version you're using so couldn't replicate the issue but I created a  test project using the version state above and it worked fine on latest API 29 Android.

**Comment by jainsahab** [comment]
Closing this issue for now. Feel free to open it again if required.
